package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"graphql/graph/model"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	c, err := r.CategoryDB.Create(ctx, input.Name, *input.Description)
	if err != nil {
		return nil, err
	}
	return &model.Category{
		ID:          c.ID,
		Name:        c.Name,
		Description: &c.Description,
	}, nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.NewCourse) (*model.Course, error) {
	c, err := r.CourseDB.Create(ctx, input.Name, *input.Description, input.CategoryID)
	if err != nil {
		return nil, err
	}
	return &model.Course{
		ID:          c.ID,
		Name:        c.Name,
		Description: &c.Description,
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categoryList, err := r.CategoryDB.FindAll(ctx)
	if err != nil {
		return nil, err
	}
	var modelCategoryList []*model.Category
	for _, category := range categoryList {
		modelCategoryList = append(modelCategoryList, &model.Category{
			ID:          category.ID,
			Name:        category.Name,
			Description: &category.Description,
		})
	}
	return modelCategoryList, nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	courseList, err := r.CourseDB.FindAll(ctx)
	if err != nil {
		return nil, err
	}
	var modelCourseList []*model.Course
	for _, course := range courseList {
		modelCourseList = append(modelCourseList, &model.Course{
			ID:          course.ID,
			Name:        course.Name,
			Description: &course.Description,
		})
	}
	return modelCourseList, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
