// Code generated by MockGen. DO NOT EDIT.
// Source: tax.go
//
// Generated by this command:
//
//	mockgen -source=tax.go -destination=mock_repository.go -package=tax
//

// Package tax is a generated GoMock package.
package tax

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// SaveTax mocks base method.
func (m *MockRepository) SaveTax(amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTax", amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTax indicates an expected call of SaveTax.
func (mr *MockRepositoryMockRecorder) SaveTax(amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTax", reflect.TypeOf((*MockRepository)(nil).SaveTax), amount)
}
